// Mapping of tickers to their actual domains for logo fetching
const tickerDomains: Record<string, string> = {
  'NVDA': 'nvidia.com',
  'MSFT': 'microsoft.com',
  'AAPL': 'apple.com',
  'AMZN': 'amazon.com',
  'GOOGL': 'google.com',
  'GOOG': 'google.com',
  'META': 'meta.com',
  'AVGO': 'broadcom.com',
  'BRK.A': 'berkshirehathaway.com', 'BRK.B': 'berkshirehathaway.com',
  'TSLA': 'tesla.com',
  'JPM': 'jpmorganchase.com',
  'WMT': 'walmart.com',
  'LLY': 'lilly.com',
  'ORCL': 'oracle.com',
  'V': 'visa.com',
  'MA': 'mastercard.com',
  'NFLX': 'netflix.com',
  'XOM': 'exxonmobil.com',
  'COST': 'costco.com',
  'JNJ': 'jnj.com',
  'HD': 'homedepot.com',
  'PLTR': 'palantir.com',
  'PG': 'pg.com',
  'BAC': 'bofa.com',
  'ABBV': 'abbvie.com',
  'CVX': 'chevron.com',
  'KO': 'coca-cola.com',
  'AMD': 'amd.com',
  'GE': 'ge.com',
  'CSCO': 'cisco.com',
  'TMUS': 't-mobile.com',
  'WFC': 'wellsfargo.com',
  'CRM': 'salesforce.com',
  'PM': 'pmi.com',
  'IBM': 'ibm.com',
  'UNH': 'unitedhealthgroup.com',
  'MS': 'morganstanley.com',
  'GS': 'goldmansachs.com',
  'INTU': 'intuit.com',
  'LIN': 'linde.com',
  'ABT': 'abbott.com',
  'AXP': 'americanexpress.com',
  'BX': 'blackstone.com',
  'DIS': 'thewaltdisneycompany.com',
  'MCD': 'mcdonalds.com',
  'RTX': 'rtx.com',
  'NOW': 'servicenow.com',
  'MRK': 'merck.com',
  'CAT': 'cat.com',
  'T': 'att.com',
  'PEP': 'pepsico.com',
  'UBER': 'uber.com',
  'BKNG': 'bookingholdings.com',
  'TMO': 'thermofisher.com',
  'VZ': 'verizon.com',
  'SCHW': 'schwab.com',
  'ISRG': 'intuitivesurgical.com',
  'QCOM': 'qualcomm.com',
  'C': 'citi.com',
  'TXN': 'ti.com',
  'BA': 'boeing.com',
  'BLK': 'blackrock.com',
  'ACN': 'accenture.com',
  'SPGI': 'spglobal.com',
  'AMGN': 'amgen.com',
  'ADBE': 'adobe.com',
  'BSX': 'bostonscientific.com',
  'SYK': 'synthes.com',
  'ETN': 'eaton.com',
  'AMAT': 'appliedmaterials.com',
  'ANET': 'arista.com',
  'NEE': 'nexteraenergy.com',
  'DHR': 'danaher.com',
  'HON': 'honeywell.com',
  'TJX': 'tjx.com',
  'PGR': 'progressive.com',
  'GILD': 'gilead.com',
  'DE': 'deere.com',
  'PFE': 'pfizer.com',
  'COF': 'capitalone.com',
  'KKR': 'kkr.com',
  'PANW': 'paloaltonetworks.com',
  'UNP': 'up.com',
  'APH': 'amphenol.com',
  'LOW': 'lowes.com',
  'LRCX': 'lamresearch.com',
  'MU': 'micron.com',
  'ADP': 'adp.com',
  'CMCSA': 'comcast.com',
  'COP': 'conocophillips.com',
  'KLAC': 'klatencor.com',
  'VRTX': 'vrtx.com',
  'MDT': 'medtronic.com',
  'SNPS': 'synopsys.com',
  'NKE': 'nike.com',
  'CRWD': 'crowdstrike.com',
  'ADI': 'analog.com',
  'WELL': 'welltower.com',
  'CB': 'chubb.com',
  'ICE': 'ice.com',
  'SBUX': 'starbucks.com',
  'TT': 'trane.com',
  'SO': 'southerncompany.com',
  'CEG': 'constellationenergy.com',
  'PLD': 'prologis.com',
  'DASH': 'doordash.com',
  'AMT': 'americantower.com',
  'MO': 'altria.com',
  'MMC': 'marshmclennan.com',
  'CME': 'cmegroup.com',
  'CDNS': 'cadence.com',
  'LMT': 'lockheedmartin.com',
  'BMY': 'bms.com',
  'WM': 'wm.com',
  'PH': 'parker.com',
  'COIN': 'coinbase.com',
  'DUK': 'duke-energy.com',
  'RCL': 'royalcaribbean.com',
  'MCO': 'moodys.com',
  'MDLZ': 'mondelezinternational.com',
  'DELL': 'dell.com',
  'TDG': 'transdigm.com',
  'CTAS': 'cintas.com',
  'INTC': 'intel.com',
  'MCK': 'mckesson.com',
  'ABNB': 'airbnb.com',
  'GD': 'gd.com',
  'ORLY': 'oreillyauto.com',
  'APO': 'apollo.com',
  'SHW': 'sherwin-williams.com',
  'HCA': 'hcahealthcare.com',
  'EMR': 'emerson.com',
  'NOC': 'northropgrumman.com',
  'MMM': '3m.com',
  'FTNT': 'fortinet.com',
  'EQIX': 'equinix.com',
  'CI': 'cigna.com',
  'UPS': 'ups.com',
  'FI': 'fiserv.com',
  'HWM': 'howmet.com',
  'AON': 'aon.com',
  'PNC': 'pnc.com',
  'CVS': 'cvs.com',
  'RSG': 'republicservices.com',
  'AJG': 'ajg.com',
  'ITW': 'itw.com',
  'MAR': 'marriott.com',
  'ECL': 'ecolab.com',
  'MSI': 'motorolasolutions.com',
  'USB': 'usbank.com',
  'WMB': 'williams.com',
  'BK': 'bnymellon.com',
  'CL': 'colgate.com',
  'NEM': 'newmont.com',
  'PYPL': 'paypal.com',
  'JCI': 'jci.com',
  'ZTS': 'zoetis.com',
  'VST': 'vistra.com',
  'EOG': 'eogresources.com',
  'CSX': 'csx.com',
  'ELV': 'elevancehealth.com',
  'ADSK': 'autodesk.com',
  'APD': 'airproducts.com',
  'AZO': 'autozone.com',
  'HLT': 'hilton.com',
  'WDAY': 'workday.com',
  'SPG': 'simon.com',
  'NSC': 'nscorp.com',
  'KMI': 'kindermorgan.com',
  'TEL': 'te.com',
  'FCX': 'fcx.com',
  'CARR': 'carrier.com',
  'PWR': 'quanta.com',
  'REGN': 'regeneron.com',
  'ROP': 'ropertechnologies.com',
  'CMG': 'chipotle.com',
  'DLR': 'digitalrealty.com',
  'MNST': 'monsterbevcorp.com',
  'TFC': 'truist.com',
  'TRV': 'travelers.com',
  'AEP': 'aep.com',
  'NXPI': 'nxp.com',
  'AXON': 'axon.com',
  'URI': 'unitedrentals.com',
  'COR': 'cencora.com',
  'FDX': 'fedex.com',
  'NDAQ': 'nasdaq.com',
  'AFL': 'aflac.com',
  'GLW': 'corning.com',
  'FAST': 'fastenal.com',
  'MPC': 'marathonpetroleum.com',
  'SLB': 'slb.com',
  'SRE': 'sempra.com',
  'PAYX': 'paychex.com',
  'PCAR': 'paccar.com',
  'MET': 'metlife.com',
  'BDX': 'bd.com',
  'OKE': 'oneok.com',
  'DDOG': 'datadoghq.com',
  // International companies
  'TSM': 'tsmc.com', 'SAP': 'sap.com', 'ASML': 'asml.com', 'BABA': 'alibaba.com', 'TM': 'toyota.com',
  'AZN': 'astrazeneca.com', 'HSBC': 'hsbc.com', 'NVS': 'novartis.com', 'SHEL': 'shell.com',
  'HDB': 'hdfcbank.com', 'RY': 'rbc.com', 'NVO': 'novonordisk.com', 'ARM': 'arm.com',
  'SHOP': 'shopify.com', 'MUFG': 'mufg.jp', 'PDD': 'pinduoduo.com', 'UL': 'unilever.com',
  'SONY': 'sony.com', 'TTE': 'totalenergies.com', 'BHP': 'bhp.com', 'SAN': 'santander.com', 'TD': 'td.com',
  'SPOT': 'spotify.com', 'UBS': 'ubs.com', 'IBN': 'icicibank.com', 'SNY': 'sanofi.com',
  'BUD': 'ab-inbev.com', 'BTI': 'bat.com', 'BN': 'brookfield.com',
  'SMFG': 'smfg.co.jp', 'ENB': 'enbridge.com', 'RELX': 'relx.com', 'TRI': 'thomsonreuters.com', 'RACE': 'ferrari.com',
  'BBVA': 'bbva.com', 'SE': 'sea.com', 'BP': 'bp.com', 'NTES': 'netease.com', 'BMO': 'bmo.com',
  'RIO': 'riotinto.com', 'GSK': 'gsk.com', 'MFG': 'mizuho-fg.com', 'INFY': 'infosys.com',
  'CP': 'cpr.ca', 'BCS': 'barclays.com', 'NGG': 'nationalgrid.com', 'BNS': 'scotiabank.com', 'ING': 'ing.com',
  'EQNR': 'equinor.com', 'CM': 'cibc.com', 'CNQ': 'cnrl.com', 'LYG': 'lloydsbankinggroup.com',
  'AEM': 'agnicoeagle.com', 'DB': 'deutsche-bank.com', 'NU': 'nu.com', 'CNI': 'cn.ca',
  'DEO': 'diageo.com', 'NWG': 'natwestgroup.com', 'AMX': 'americamovil.com', 'MFC': 'manulife.com',
  'E': 'eni.com', 'WCN': 'wasteconnections.com', 'SU': 'suncor.com', 'TRP': 'tcenergy.com', 'PBR': 'petrobras.com',
  'HMC': 'honda.com', 'GRMN': 'garmin.com', 'CCEP': 'coca-colaep.com', 'ALC': 'alcon.com', 'TAK': 'takeda.com'
};

export function getLogoUrl(ticker: string): string {
  const domain = tickerDomains[ticker] ?? `${ticker.toLowerCase()}.com`;
  
  // Special handling for problematic tickers with alternative domains
  if (ticker === 'BAC') {
    return `https://logo.clearbit.com/bofa.com?size=32`;
  }
  if (ticker === 'DB') {
    return `https://logo.clearbit.com/deutsche-bank.com?size=32`;
  }
  if (ticker === 'VRTX') {
    return `https://logo.clearbit.com/vrtx.com?size=32`;
  }
  if (ticker === 'CTAS') {
    return `https://logo.clearbit.com/cintas.com?size=32`;
  }
  if (ticker === 'ROP') {
    return `https://logo.clearbit.com/ropertechnologies.com?size=32`;
  }
  if (ticker === 'COR') {
    return `https://logo.clearbit.com/cencora.com?size=32`;
  }
  if (ticker === 'MFG') {
    return `https://logo.clearbit.com/mizuho-fg.com?size=32`;
  }
  if (ticker === 'CCEP') {
    return `https://logo.clearbit.com/coca-colaep.com?size=32`;
  }
  
  return `https://logo.clearbit.com/${domain}?size=32`;
} 